export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

export const GET_NOTE_LIST = 'GET_NOTE_LIST';
export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS';
export const GET_NOTE_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const GET_NOTES_BY_TITLE = 'GET_NOTES_BY_TITLE';
export const GET_NOTES_BY_TITLE_SUCCESS = 'GET_NOTES_BY_TITLE_SUCCESS';
export const GET_NOTES_BY_TITLE_FAIL = 'GET_NOTES_BY_TITLE_FAIL';

export const GET_NOTES_BY_CATEGORY = 'GET_NOTES_BY_CATEGORY';
export const GET_NOTES_BY_CATEGORY_SUCCESS = 'GET_NOTES_BY_CATEGORY_SUCCESS';
export const GET_NOTES_BY_CATEGORY_FAIL = 'GET_NOTES_BY_CATEGORY_FAIL';

export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';
